<?php

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="weather-body" data-bind="scope: 'weather-component'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app":  <?= /* @escapeNotVerified */$block->getJsLayout(); ?>
        }
    }
</script>

